#  Here we do modular coding for data ingestion

artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/file/d/1wG9AZfjeIqet4_VlnNUNCqonqqufx9tg/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


# for base model
prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5

# For training model

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/traning/model.h5